### ISSUE TITLE
Evaluation with larger batch size

### ISSUE THREAD

**Issue by prakamya-mishra** [princeton-nlp/HELMET#9]
How can I do the evaluation on larger batch size to utilize my all the GPUs better in the multi-GPU setting?

**Comment by howard-yen** [comment]
Thanks for your interest in our work! The code currently does not support larger batch sizes as we use multi-GPU for model parallelism to accommodate longer sequences. In the future, I do plan on adding support for multi-GPU runs for faster inference, please stay tuned! In the meantime, the best way to utilize multiple GPUs is to run multiple jobs, each with a different dataset or setting, for example.
